adapt to https+auth
hugegraph/hugegraph-client pull request #109
Opened 2020-11-16 10:23 UTC by zhoney

Change-Id: Ied484f2121a731e312868b6fcd89b790b8465dd2

2020-11-16 12:00 UTC, javeme requested changes

2020-11-16 12:00 UTC, javeme commented on src/test/java/com/baidu/hugegraph/functional/HugeClientHttpsTest.java
> +                      .configSSL("","")
missing a space

2020-11-16 12:49 UTC, javeme approved these changes

2020-11-17 01:37 UTC, houzhizhen approved these changes

2020-11-17 09:22 UTC, Linary approved these changes

2020-11-18 02:49 UTC, houzhizhen approved these changes

2020-11-18 03:04 UTC, Linary approved these changes

2020-11-18 06:50 UTC, javeme approved these changes

2020-11-18 06:53 UTC, merged