match server https certificate
hugegraph/hugegraph-client pull request #110
Opened 2020-11-19 08:35 UTC by shzcore

2020-11-19 09:54 UTC, Linary requested changes

2020-11-19 09:54 UTC, Linary commented on assembly/travis/install-hugegraph.sh
> +echo "ssl.keystore_file=conf/hugegraph-server.keystore" >> $REST_SERVER_CONFIG
adapt for newly server

2020-11-20 03:05 UTC, javeme submitted a review, later dismissed

2020-11-20 03:07 UTC, Linary submitted a review, later dismissed

2020-11-21 06:00 UTC, Linary approved these changes

2020-11-23 03:03 UTC, javeme approved these changes

2020-11-23 03:03 UTC, merged