modifty kout request param order
hugegraph/hugegraph-client pull request #112
Opened 2020-12-01 08:49 UTC by shzcore

2020-12-04 11:40 UTC, javeme submitted a review, later dismissed

2020-12-04 11:41 UTC, Linary submitted a review, later dismissed

2020-12-11 12:36 UTC, javeme commented
CI fails:
![image](https://user-images.githubusercontent.com/9625821/101904218-7b320e80-3bf0-11eb-8885-127fa76cf8df.png)

2020-12-11 13:31 UTC, javeme requested changes

2020-12-11 13:31 UTC, javeme commented on src/test/java/com/baidu/hugegraph/api/traverser/KoutApiTest.java
> +                    "but got capacity '-1' and limit '1'";
align with "Capacity..."

2020-12-11 13:31 UTC, javeme commented on src/test/java/com/baidu/hugegraph/api/traverser/KoutApiTest.java
> +                    "but got capacity '-1' and limit '1'";
@zhoney does capacity=-1 means capacity > limit 1

2020-12-14 07:52 UTC, zhoney requested changes

2020-12-14 07:52 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/api/traverser/KoutApiTest.java
>      }
add one test with capacity 1 and limit -1 to ensure limit can't be NO_LIMIT when capacity is not NO_LIMIT

2020-12-14 07:52 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/api/traverser/KoutAPI.java
rebase #113

2020-12-15 11:23 UTC, javeme approved these changes

2020-12-15 11:36 UTC, zhoney approved these changes

2020-12-15 11:37 UTC, merged