add login api
hugegraph/hugegraph-client pull request #125
Opened 2021-06-15 11:45 UTC by corgiboygsj

2021-06-15 14:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/structure/auth/LoginResult.java
> +    private String token;
add user_id?

2021-06-16 09:13 UTC, corgiboygsj commented on src/main/java/com/baidu/hugegraph/structure/auth/LoginResult.java
> +    private String token;
only return token in login method

2021-06-16 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/api/auth/LoginAPI.java
> +        String path = String.join("/", this.path(), "logout");
also update login path

2021-06-17 06:48 UTC, Linary requested changes

2021-06-17 06:48 UTC, Linary commented on pom.xml
> +        <hugegraph.common.version>1.8.9</hugegraph.common.version>
upgrade client version to 1.9.5

2021-06-17 08:32 UTC, javeme commented on src/main/java/com/baidu/hugegraph/api/auth/TokenVerifyAPI.java
> +    public Map<String, Object> verifyToken() {
define a class and return its instance

2021-06-17 08:32 UTC, javeme commented on src/main/java/com/baidu/hugegraph/api/auth/TokenVerifyAPI.java
> +public class TokenVerifyAPI extends AuthAPI {
prefer TokenAPI

2021-06-17 08:32 UTC, javeme commented on src/main/java/com/baidu/hugegraph/driver/AuthManager.java
> +        this.tokenVerifyAPI = new TokenVerifyAPI(client, graph);
rename to tokenAPI

2021-06-17 09:44 UTC, javeme commented on src/main/java/com/baidu/hugegraph/api/auth/TokenAPI.java
> +        return TokenPayload.fromMap(result.readObject(Map.class));
result.readObject(TokenPayload.class)

2021-06-17 09:44 UTC, javeme commented on src/main/java/com/baidu/hugegraph/structure/auth/TokenPayload.java
> +    public static TokenPayload fromMap(Map<String, Object> map) {
delete this method

2021-06-17 13:15 UTC, javeme approved these changes

2021-06-25 07:07 UTC, javeme approved these changes

2021-06-25 07:14 UTC, Linary approved these changes

2021-06-25 07:15 UTC, merged